# AUTO-GENERATED — DO NOT EDIT
from typing import Any, Dict

CONFIG: Dict[str, Any] = {'ACCOUNT_CAPITAL': 10000, 'ACCOUNT_ID': 0, 'API_KEY': '', 'SECRET_TOKEN': '', 'REFRESH_TOKEN': '', 'ENABLE_LIVE_TRADING': False, 'PUSHOVER_USER_KEY': '', 'PUSHOVER_API_TOKEN': '', 'ADMIN_PUSHOVER_USER_KEY': 'uck9cc5jyue5oir91izu2ordr6s4uc', 'ADMIN_PUSHOVER_API_TOKEN': 'admisid7fij7jfsnc8tavqa1wf2ghi', 'PUSHOVER_ENABLED': True, 'WINDOWS_ALERT_ENABLED': True, 'POSITIONS': 1, 'MIN_EM': 8, 'MAX_PREMIUM': 200, 'PROFIT_MULTIPLIER': 1.2, 'SPREAD_WIDTH': 10, 'SLIPPAGE': 0.05, 'BID_ASK_SPREAD': 2, 'STRIKE_STEP': 5, 'STRIKE_RANGE': 3, 'MAX_CALLS_ACTIVE': 2, 'MAX_PUTS_ACTIVE': 2, 'MARKET_OPEN_TIME': '09:30:00', 'TRADE_START_TIME': '10:00:00', 'STOP_NEW_ENTRIES': '14:30:00', 'FORCE_EXIT_TIME': '14:45:00', 'FORCE_EXIT_ENABLED': True, 'ORDER_TIMEOUT': 180, 'LOOP': 2, 'NOISE_3_5': 0.25, 'NOISE_5_20': 0.25, 'EMA20_ADJUSTMENT': 0, 'EMA_MAX_STALENESS_DAYS': 1, 'EMA_FILE': 'ema_state.json', 'EMA_REBUILD_DEPTH': 120, 'ORDER_RETRY_ATTEMPTS': 3, 'TOKEN_REFRESH_DELAY': 1, 'DATA_RETRY_ATTEMPTS': 3, 'DATA_RETRY_DELAY': 0.5, 'MAX_API_FAILURES': 5}

ACCOUNT_CAPITAL = 10000
ACCOUNT_ID = 0
API_KEY = ''
SECRET_TOKEN = ''
REFRESH_TOKEN = ''
ENABLE_LIVE_TRADING = False
PUSHOVER_USER_KEY = ''
PUSHOVER_API_TOKEN = ''
ADMIN_PUSHOVER_USER_KEY = 'uck9cc5jyue5oir91izu2ordr6s4uc'
ADMIN_PUSHOVER_API_TOKEN = 'admisid7fij7jfsnc8tavqa1wf2ghi'
PUSHOVER_ENABLED = True
WINDOWS_ALERT_ENABLED = True
POSITIONS = 1
MIN_EM = 8
MAX_PREMIUM = 200
PROFIT_MULTIPLIER = 1.2
SPREAD_WIDTH = 10
SLIPPAGE = 0.05
BID_ASK_SPREAD = 2
STRIKE_STEP = 5
STRIKE_RANGE = 3
MAX_CALLS_ACTIVE = 2
MAX_PUTS_ACTIVE = 2
MARKET_OPEN_TIME = '09:30:00'
TRADE_START_TIME = '10:00:00'
STOP_NEW_ENTRIES = '14:30:00'
FORCE_EXIT_TIME = '14:45:00'
FORCE_EXIT_ENABLED = True
ORDER_TIMEOUT = 180
LOOP = 2
NOISE_3_5 = 0.25
NOISE_5_20 = 0.25
EMA20_ADJUSTMENT = 0
EMA_MAX_STALENESS_DAYS = 1
EMA_FILE = 'ema_state.json'
EMA_REBUILD_DEPTH = 120
ORDER_RETRY_ATTEMPTS = 3
TOKEN_REFRESH_DELAY = 1
DATA_RETRY_ATTEMPTS = 3
DATA_RETRY_DELAY = 0.5
MAX_API_FAILURES = 5

__all__ = ['CONFIG'] + ['ACCOUNT_CAPITAL', 'ACCOUNT_ID', 'API_KEY', 'SECRET_TOKEN', 'REFRESH_TOKEN', 'ENABLE_LIVE_TRADING', 'PUSHOVER_USER_KEY', 'PUSHOVER_API_TOKEN', 'ADMIN_PUSHOVER_USER_KEY', 'ADMIN_PUSHOVER_API_TOKEN', 'PUSHOVER_ENABLED', 'WINDOWS_ALERT_ENABLED', 'POSITIONS', 'MIN_EM', 'MAX_PREMIUM', 'PROFIT_MULTIPLIER', 'SPREAD_WIDTH', 'SLIPPAGE', 'BID_ASK_SPREAD', 'STRIKE_STEP', 'STRIKE_RANGE', 'MAX_CALLS_ACTIVE', 'MAX_PUTS_ACTIVE', 'MARKET_OPEN_TIME', 'TRADE_START_TIME', 'STOP_NEW_ENTRIES', 'FORCE_EXIT_TIME', 'FORCE_EXIT_ENABLED', 'ORDER_TIMEOUT', 'LOOP', 'NOISE_3_5', 'NOISE_5_20', 'EMA20_ADJUSTMENT', 'EMA_MAX_STALENESS_DAYS', 'EMA_FILE', 'EMA_REBUILD_DEPTH', 'ORDER_RETRY_ATTEMPTS', 'TOKEN_REFRESH_DELAY', 'DATA_RETRY_ATTEMPTS', 'DATA_RETRY_DELAY', 'MAX_API_FAILURES']
